{% set phpVersion = imageName|split('_')|last %}
{% set phpMajor = phpVersion|split('.')[0] %}
{% set phpMinor = phpVersion|split('.')[1] %}
{% set mysqlVersion = imageName|split('_')[2] %}

FROM ubuntu:22.04

RUN apt-get update && apt-get install make

RUN mkdir -p /run/php/

{#Install PHP#}
RUN apt-get update
RUN apt install -y software-properties-common
RUN add-apt-repository ppa:ondrej/php
RUN apt-get update --fix-missing

RUN apt install -y php{{ phpVersion }}-fpm
UN apt-get install -y php{{ phpVersion }}-iconv
RUN apt-get install -y php{{ phpVersion }}-mysqli
RUN apt-get install -y php{{ phpVersion }}-gd
RUN apt-get install -y php{{ phpVersion }}-mbstring
RUN apt-get install -y php{{ phpVersion }}-zip
RUN apt-get install -y php{{ phpVersion }}-soap
RUN apt-get install -y php{{ phpVersion }}-pdo
RUN apt-get install -y php{{ phpVersion }}-curl
RUN apt-get install -y php{{ phpVersion }}-dom
RUN apt-get install -y php{{ phpVersion }}-simplexml
RUN apt-get install -y php{{ phpVersion }}-xml
RUN apt-get install -y php{{ phpVersion }}-intl
RUN php -v

RUN ln -s /usr/sbin/php-fpm{{ phpVersion }} /usr/sbin/php-fpm

RUN apt-get update && apt-get install -y --no-install-recommends \
    git \
    ssl-cert \
    nginx \
    supervisor \
    libwebp-dev \
    gettext-base \
    zlib1g-dev \
    libzip-dev \
    libfreetype6-dev \
    libpng-dev \
    libicu-dev \
    libbz2-dev \
    libxml2-dev \
    sudo \
    wget \
    curl

RUN rm -rf /tmp/*
RUN chown -R www-data:www-data /var/www
RUN usermod -u 1000 www-data

{% if mysqlVersion < 8 %}
    RUN sudo apt-get clean
    RUN curl -LsS https://r.mariadb.com/downloads/mariadb_repo_setup | sudo bash -s -- --mariadb-server-version="mariadb-10.3" --os-type=debian --os-version=buster --write-to-stdout
    RUN DEBIAN_FRONTEND=noninteractive apt -y install mariadb-server mariadb-client
{% else %}
    RUN yes | apt install mariadb-server mariadb-client
{% endif %}


RUN curl -fsSL https://deb.nodesource.com/setup_16.x | sudo -E bash -
RUN sudo apt-get install -y nodejs
RUN echo "NODE Version:" && node --version
RUN echo "NPM Version:" && npm --version


RUN curl -sS https://getcomposer.org/installer -o /tmp/composer-setup.php
RUN php /tmp/composer-setup.php --install-dir=/usr/local/bin --filename=composer


COPY rootfs/ /
EXPOSE 80
WORKDIR /var/www/html

CMD ["/usr/bin/supervisord", "-c", "/etc/supervisord.conf"]
